modLoader="scorge"
loaderVersion="[3.1,)"
issueTrackerURL="https://github.com/MrTJP/ProjectRed"

[[mods]]
    modId="projectred-integration"
    displayName="ProjectRed Integration"
    entryClass="mrtjp.projectred.ProjectRedIntegration"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-integration]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbm_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="projectred-core"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"
