modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MrTJP/ProjectRed"
license="MIT"

[[mods]]
    modId="projectred-expansion"
    displayName="ProjectRed Expansion"
    entryClass="mrtjp.projectred.ProjectRedExpansion"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-expansion]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-expansion]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-expansion]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbm_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-expansion]]
    modId="projectred-core"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"